<?php
/*
Plugin Name: Tango Smileys Extended
Plugin URI: http://munashiku.slightofmind.net/wordpress-plugins/tango-smileys-extended
Description: Replace the standard WP Smileys with Tango PNG smileys. Extends smileys from 18 to 202! <strong>For WordPress 2.8+</strong>
Version: 2.6.4.1
Author: Whesley McCabe
Author URI: http://munashiku.slightofmind.net/
*/

/*
#	This file provides structure for Tango Smileys Extended.
#	Please do not edit this file.
*/

// Provide Upgrade Version
global $tse_version;
$tse_version = '2641';

// Get Includes
include_once( 'tse-options.php' );
include_once( 'tse-magic.php' );
include_once( 'tse-cti.php' );

// Options Page: Settings -> Tango Smileys Extended
function tse_add_options_submenu() {
	$tse_options_page = add_submenu_page( 'options-general.php', 'Tango Smileys Extended: Options', 'Tango Smileys Extended', 10, 'tango-smileys-extended', 'tse_options' );
	add_action( "admin_print_scripts-$tse_options_page", 'tse_options_script' );
	add_action( "admin_print_styles-$tse_options_page", 'tse_options_style' );
}

// Ozh Admin Drop Down Menu: TSE Icon
function tse_icon( $tseiconhook ) {
	if ( $tseiconhook == 'tango-smileys-extended' ) return plugins_url( 'tseicon.png', __FILE__ );
	return $tseiconhook;
}

// Filters & Actions: Enable / Disable
function tse_filters() {
	$tse = get_option( 'tango_smileys_extended' );
	if ( $tse['posts'] == 'on' || $tse['pages'] == 'on' ) {
		update_option( 'use_smilies', 0 );
		add_filter( 'the_content', 'tse_conditional' );
		add_action( 'admin_head', 'tse_htmled_css' );
		add_action( 'admin_footer', 'tse_htmled_script' );
		add_action( 'init', 'tse_tinymce_addbuttons' );
	}
	if ( $tse['comments'] == 'on' ) {
		update_option( 'use_smilies', 0 );
		add_filter( 'comment_text', 'tse_switcher' );
		if ( $tse['comments_cti'] == 'on' ) {
			if ( $tse['comments_mce'] == 'on' ) {
				add_action( 'comment_form', 'tse_add_mce_smileys' );
			}
			else {
				add_action( 'comment_form', 'tse_add_cti_smileys' );
			}
			add_action( 'wp_head', 'CTIStyle' );
		}
	}
}

// Add TSE to the TinyMCE plugin list and add a button
function tse_tinymce_addbuttons() {
	global $pagenow;
	if ( !current_user_can( 'edit_posts' ) && !current_user_can( 'edit_pages' ) ) {
		return;
	}
	if ( get_user_option( 'rich_editing' ) == 'true' ) {
		$tse = get_option( 'tango_smileys_extended' );
		$post_editor  = ( in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) && $tse['posts_cti'] == 'on' );
		$page_editor  = ( in_array( $pagenow, array( 'page.php', 'page-new.php' ) ) && $tse['pages_cti'] == 'on' );
		if ( $post_editor || $page_editor ) {
			add_filter( 'mce_external_plugins', 'tse_tinymce_addplugin' );
			add_filter( 'mce_buttons', 'tse_tinymce_registerbutton' );
		}
	}
}
function tse_tinymce_registerbutton( $buttons ) {
	array_push( $buttons, 'separator', 'tse' );
	return $buttons;
}
function tse_tinymce_addplugin( $plugin_array ) {
	$tse = get_option( 'tango_smileys_extended' );
	$tse_smileypx = ( $tse['smileysize'] == '24' ) ? '?smileysize=24' : '';
	$plugin_array['tse'] = plugins_url( "tse-mce-plugin.php{$tse_smileypx}", __FILE__ );
	return $plugin_array;
}

// Add TSE to the HTML editor for posts and pages.
function tse_htmled_css() {
	global $pagenow;
	$tse = get_option( 'tango_smileys_extended' );
	$post_editor  = ( in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) && $tse['posts_cti'] == 'on' );
	$page_editor  = ( in_array( $pagenow, array( 'page.php', 'page-new.php' ) ) && $tse['pages_cti'] == 'on' );
	if ( $post_editor || $page_editor ) {
		$tseicon = plugins_url( 'tseicon.png', __FILE__ );
echo <<<CSS
	<style type='text/css'>
		#ed_tse {
			background: url($tseicon) no-repeat center center !important;
		}
		#tse_htmled_smileys {
			border-color: #ccc !important;
			height: 260px;
			left: 0px;
			position: absolute;
			top: 0px;
			visibility: hidden;
			width: 368px;
		}
		#tse_htmled_smileys .inside {
			height: 220px;
			overflow: auto;
			position: absolute;
		}
		.htmlcti {
			padding: 4px !important;
			text-align: center;
		}
		.htmlcti img {
			padding: 1px;
		}
		.tse_title {
			background: #dfdfdf;
			font-size: 12px;
			font-weight: bold;
			padding: 6px;
			text-align: center;
			text-shadow: #fff 0 1px 0;
			-moz-border-radius: 6px 6px 0 0;
			-webkit-border-top-right-radius: 6px;
			-webkit-border-top-left-radius: 6px;
			-khtml-border-top-right-radius: 6px;
			-khtml-border-top-left-radius: 6px;
			border-top-right-radius: 6px;
			border-top-left-radius: 6px;
		}
	</style>
CSS;
	}
}

function tse_htmled_script() {
	global $pagenow;
	$tse = get_option( 'tango_smileys_extended' );
	$post_editor  = ( in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) && $tse['posts_cti'] == 'on' );
	$page_editor  = ( in_array( $pagenow, array( 'page.php', 'page-new.php' ) ) && $tse['pages_cti'] == 'on' );
	if ( $post_editor || $page_editor ) {
		echo '<script language="javascript" type="text/javascript" src="' . plugins_url( 'tse-htmled.js', __FILE__ ) . '"></script>';
		echo "<div id='tse_htmled_smileys' class='postbox'><div class='tse_title'>Tango Smileys Extended</div><div class='inside htmlcti'>";
		tse_cti_anywhere( 'content', true, 'all' );
		echo "</div></div>";
echo <<<SCRIPT
	<script language="javascript" type="text/javascript">
	//<![CDATA[
		if(document.getElementById("ed_toolbar")){
			qt_toolbar = document.getElementById("ed_toolbar");
			edButtons[edButtons.length] = new edButton("ed_tse","Tango Smileys", "", "", "");
			var qt_button = qt_toolbar.lastChild;
			while (qt_button.nodeType != 1){
				qt_button = qt_button.previousSibling;
			}
			qt_button = qt_button.cloneNode(true);
			qt_button.value = " ";
			qt_button.title = "Tango Smileys";
			qt_button.onclick = function () {}
			qt_button.id = "ed_tse";
			qt_toolbar.appendChild(qt_button);
		}
		at_attach("ed_tse", "tse_htmled_smileys", "click", "y", "pointer");
	//]]>
	</script>
SCRIPT;
	}
}

// Convert shorthand in posts and/or pages?
function tse_conditional( $tse_content ) {
	global $wp_query;
	$tse = get_option( 'tango_smileys_extended' );
	$tse_posts = ( $tse['posts'] == 'on' ? true : false );
	$tse_pages = ( $tse['pages'] == 'on' ? true : false );
	$tse_ispage = $wp_query->is_page;
	$tse_content = ( ( !$tse_ispage && $tse_posts ) || ( $tse_ispage && $tse_pages ) ) ? tse_switcher( $tse_content ) : $tse_content;
	return $tse_content;
}

// Activate or Upgrade Options
function tse_activate() {
	global $tse_version;
	$tse_old = get_option( 'tango_smileys_extended' );
	if ( is_array( $tse_old ) && !isset( $tse_old['version'] ) ) {
		$tse_new['version']      = $tse_version;
		$tse_new['wp_smilies']   = ( $tse_old['wp_smilies_on'] == '' ? 'off' : $tse_old['wp_smilies_on'] );
		$tse_new['posts']        = ( $tse_old['tse_content_on'] == '' ? 'on' : $tse_old['tse_content_on'] );
		$tse_new['pages']        = $tse_new['posts'];
		$tse_new['comments']     = ( $tse_old['tse_comments_on'] == '' ? 'on' : $tse_old['tse_comments_on'] );
		$tse_new['smileysize']   = '16';
		$tse_new['posts_cti']    = ( $tse_old['tse_content_on'] == '' ? 'on' : $tse_old['tse_content_on'] );
		$tse_new['pages_cti']    = $tse_new['posts_cti'];
		$tse_new['comments_cti'] = ( $tse_old['tse_comments_cti'] == '' ? 'on' : $tse_old['tse_comments_cti'] );
		$tse_new['comments_mce'] = ( $tse_old['tse_comments_mce'] == '' ? '' : $tse_old['tse_comments_mce'] );
		$tse_new['cti_width']    = ( $tse_old['tse_cti_width'] == '' ? '420' : $tse_old['tse_cti_width'] );
		$tse_new['cti_height']   = ( $tse_old['tse_cti_height'] == '' ? '36' : $tse_old['tse_cti_height'] );
		$tse_new['cti_bg']       = ( $tse_old['tse_cti_bg'] == '' ? 'transparent' : $tse_old['tse_cti_bg'] );
		$tse_new['cti_borders']  = ( $tse_old['tse_cti_borders'] == '' ? '0' : $tse_old['tse_cti_borders'] );
		$tse_new['cti_bordert']  = ( $tse_old['tse_cti_bordert'] == '' ? 'solid' : $tse_old['tse_cti_bordert'] );
		$tse_new['cti_borderc']  = ( $tse_old['tse_cti_borderc'] == '' ? 'black' : $tse_old['tse_cti_borderc'] );
		$tse_new['cti_header']   = ( $tse_old['tse_cti_header'] == '' ? 'Click to Insert Smiley' : $tse_old['tse_cti_header'] );
		delete_option( 'tango_smileys_extended' );
	}
	elseif ( isset( $tse_old['version'] ) && $tse_old['version'] < $tse_version ) {
		$tse_new = $tse_old;
		if ( $tse_new['version'] < '2620' ) {
			$tse_new['smileysize'] = '16';
		}
		if ( $tse_new['version'] < '2640' ) {
			$tse_new['standard']   = 'on';
			$tse_new['extended']   = 'on';
			$tse_new['gestures']   = 'on';
			$tse_new['special']    = 'on';
			$tse_new['animals']    = 'on';
			$tse_new['foodndrink'] = 'on';
			$tse_new['other']      = 'on';
		}
		$tse_new['version'] = $tse_version;
	}
	else {
		$tse_new = array(
			'version'      => $tse_version,
			'wp_smilies'   => '',
			'posts'        => 'on',
			'pages'        => 'on',
			'comments'     => 'on',
			'smileysize'   => '16',
			'posts_cti'    => 'on',
			'pages_cti'    => 'on',
			'comments_cti' => 'on',
			'comments_mce' => '',
			'cti_width'    => '420',
			'cti_height'   => '36',
			'cti_bg'       => 'transparent',
			'cti_borders'  => '0',
			'cti_bordert'  => 'solid',
			'cti_borderc'  => 'black',
			'cti_header'   => 'Click to Insert Smiley',
			'standard'     => 'on',
			'extended'     => 'on',
			'gestures'     => 'on',
			'special'      => 'on',
			'animals'      => 'on',
			'foodndrink'   => 'on',
			'other'        => 'on'
		);
	}
	update_option( 'tango_smileys_extended', $tse_new );
}

add_action( 'admin_menu', 'tse_add_options_submenu' );
add_filter( 'ozh_adminmenu_icon_tango-smileys-extended', 'tse_icon' );
tse_filters();
register_activation_hook( __FILE__, 'tse_activate' );

?>