<?php
/*
#	This file controls the setting of the options for Tango Smileys Extended.
#	Please do not edit this file.
*/

add_action( 'admin_init', 'tse_options_init' );

function tse_options_init() {
	register_setting( 'tse_options_options', 'tango_smileys_extended' ); // Optional 3rd arg: Validation
}

function tse_options() {
	?>
<div class="wrap">
	<h2>Tango Smileys Extended: Options</h2>
	<form method="post" action="options.php" name="tse_options">
		<?php settings_fields( 'tse_options_options' ); ?>
		<?php $tse = get_option( 'tango_smileys_extended' ); ?>
		<h3>General Options</h3>
		<table class="form-table" width="100%" border="0"><tbody>
			<tr>
				<th scope="row">Use Default WordPress Smilies?</th>
				<td>
					<input type="checkbox" id="wp_smilies" name="tango_smileys_extended[wp_smilies]" <?php checked( 'on', $tse['wp_smilies'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[wp_smilies]">Use Default <small class="red">Notice: This will disable TSE!</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Enable <acronym title="Tango Smileys Extended">TSE</acronym> in:</th>
				<td>
					<input type="checkbox" id="tse_posts" name="tango_smileys_extended[posts]" <?php checked( 'on', $tse['posts'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[posts]">Posts</label>
					<br />
					<input type="checkbox" id="tse_pages" name="tango_smileys_extended[pages]" <?php checked( 'on', $tse['pages'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[pages]">Pages</label>
					<br />
					<input type="checkbox" id="tse_comments" name="tango_smileys_extended[comments]" <?php checked( 'on', $tse['comments'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[comments]">Comments</label>
				</td>
			</tr>
			<tr>
				<th scope="row">Smiley Size:</th>
				<td>
					<input type="radio" name="tango_smileys_extended[smileysize]" value="16" <?php checked( '16', $tse['smileysize'] ); ?> />
					<label for="tango_smileys_extended[smileysize]">16px</label>
					<br />
					<input type="radio" name="tango_smileys_extended[smileysize]" value="24" <?php checked( '24', $tse['smileysize'] ); ?> />
					<label for="tango_smileys_extended[smileysize]">24px</label>
				</td>
			</tr>
			<tr>
				<th scope="row">Enable <acronym title="Click to Insert">CTI</acronym> in:</th>
				<td>
					<input type="checkbox" id="tse_posts_cti" name="tango_smileys_extended[posts_cti]" <?php checked( 'on', $tse['posts_cti'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[posts_cti]">Posts</label>
					<br />
					<input type="checkbox" id="tse_pages_cti" name="tango_smileys_extended[pages_cti]" <?php checked( 'on', $tse['pages_cti'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[pages_cti]">Pages</label>
					<br />
					<input type="checkbox" id="tse_comments_cti" name="tango_smileys_extended[comments_cti]" <?php checked( 'on', $tse['comments_cti'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[comments_cti]">Comments</label>
					<br />
					<input type="checkbox" id="tse_comments_mce" name="tango_smileys_extended[comments_mce]" <?php checked( 'on', $tse['comments_mce'] ); ?> onclick="checkit(this.id);" />
					<label for="tango_smileys_extended[comments_mce]">MCEComments</label>
				</td>
			</tr>
		</tbody></table>
		<h3>CTI Options</h3>
		<table class="form-table" width="100%" border="0"><tbody>
			<tr>
				<th scope="row">Header Text:</th>
				<td>
					<input type="text" name="tango_smileys_extended[cti_header]" value="<?php echo $tse['cti_header']; ?>" size="30" maxlength="100" />
					<label for="tango_smileys_extended[cti_header]">Placed above the CTI box. <small class="blue">[Default=Click to Insert Smiley]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Width:</th>
				<td>
					<input type="text" name="tango_smileys_extended[cti_width]" value="<?php echo $tse['cti_width']; ?>" size="30" maxlength="4" />
					<label for="tango_smileys_extended[cti_width]">in Pixels (Numbers ONLY) <small class="blue">[Default=420]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Height:</th>
				<td>
					<input type="text" name="tango_smileys_extended[cti_height]" value="<?php echo $tse['cti_height']; ?>" size="30" maxlength="3" />
					<label for="tango_smileys_extended[cti_height]">in Pixels (Numbers ONLY) <small class="blue">[Default=36]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Background:</th>
				<td>
					<input type="text" name="tango_smileys_extended[cti_bg]" value="<?php echo $tse['cti_bg']; ?>" size="30" maxlength="100" />
					<label for="tango_smileys_extended[cti_bg]"></label>Any valid css value for BACKGROUND <small class="blue">[Default=transparent]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Border Size:</th>
				<td>
					<input type="text" name="tango_smileys_extended[cti_borders]" value="<?php echo $tse['cti_borders']; ?>" size="30" maxlength="2" />
					<label for="tango_smileys_extended[cti_borders]">Any valid css value for BORDER size <small class="blue">[Default=0]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Border Type:</th>
				<td>
					
					<input type="text" name="tango_smileys_extended[cti_bordert]" value="<?php echo $tse['cti_bordert']; ?>" size="30" maxlength="12" />
					<label for="tango_smileys_extended[cti_bordert]">Any valid css value for BORDER type <small class="blue">[Default=solid]</small></label>
				</td>
			</tr>
			<tr>
				<th scope="row">Border Color:</th>
				<td>
					
					<input type="text" name="tango_smileys_extended[cti_borderc]" value="<?php echo $tse['cti_borderc']; ?>" size="30" maxlength="30" />
					<label for="tango_smileys_extended[cti_borderc]">Any valid css value for BORDER color <small class="blue">[Default=black]</small></label>
				</td>
			</tr>
			<tr>
				<td colspan="2"><h4>Enable Which Smileys for Comments?</h4></td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[standard]" <?php checked( 'on', $tse['standard'] ); ?> />
					<label for="tango_smileys_extended[standard]">Standard:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'standard' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[extended]" <?php checked( 'on', $tse['extended'] ); ?> />
					<label for="tango_smileys_extended[extended]">Extended:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'extended' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[gestures]" <?php checked( 'on', $tse['gestures'] ); ?> />
					<label for="tango_smileys_extended[gestures]">Gestures:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'gestures' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[special]" <?php checked( 'on', $tse['special'] ); ?> />
					<label for="tango_smileys_extended[special]">Special:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'special' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[animals]" <?php checked( 'on', $tse['animals'] ); ?> />
					<label for="tango_smileys_extended[animals]">Animals:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'animals' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[foodndrink]" <?php checked( 'on', $tse['foodndrink'] ); ?> />
					<label for="tango_smileys_extended[foodndrink]">Food and Drink:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'foodndrink' ); ?></div>
				</td>
			</tr>
			<tr>
				<th scope="row">
					<input type="checkbox" name="tango_smileys_extended[other]" <?php checked( 'on', $tse['other'] ); ?> />
					<label for="tango_smileys_extended[other]">Other:</label>
				</th>
				<td>
					<div style="width: 400px;"><?php tse_options_smiley_showcase( 'other' ); ?></div>
				</td>
			</tr>
		</tbody></table>
		<p class="submit"><input type="submit" class="button-primary" value="Update Options &raquo;" /></p>
	</form>
</div>
	<?php
}

// Optional Validation for register_setting()
function tse_options_validate( $tse ) {
	$tse['cti_header'] = wp_filter_nohtml_kses( $tse['cti_header'] );
	return $tse;
}

function tse_options_script() {
	echo '<script type="text/javascript" src="' . plugins_url( 'tse-options.js', __FILE__ ) . '"></script>';
}

function tse_options_style() {
	?>
	<style type="text/css">
	th {
		width: 240px;
	}
	small.red {
		color: red;
	}
	small.blue {
		color: blue;
	}
	</style>
	<?php
}

function tse_options_smiley_showcase( $tse_option ) {
	$tse_smileys = tseCTI_get_smileys( $tse_option );
	$smileysout = '';
	for ( $i = 0; $i < sizeof( $tse_smileys ); $i++ ) {
		$currentsmiley = plugins_url( "/tango/{$tse_smileys[$i][1]}", __FILE__ );
		$tse_img_full = "<img src='$currentsmiley' alt='{$tse_smileys[$i][2]}' title='{$tse_smileys[$i][2]} ( {$tse_smileys[$i][0]} )' />";
		$smileysout .= $tse_img_full;
	}
	echo $smileysout;
}

?>