<?php
/*
#	This file allows for Tango Smileys Extended to be uninstalled.
#	Please do not edit this file.
*/

if( !defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit();
}

delete_option( 'tango_smileys_extended' );

?>